version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_plugins.yaml
    flatten: true
    excludes: [] # put task names in here which are overwritten in this file
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/pkg/...'
      COMPONENTS: 'scim'
      GENERATE_DOCS_INDEX: "false"

