version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_service.yaml
    flatten: true
    excludes: [] # put task names in here which are overwritten in this file
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/test/...'
      COMPONENTS: 'identity-management'
      REPO_URL: 'https://github.com/openkcm/identity-management-plugins'
      GENERATE_DOCS_INDEX: "false"

