name: Labeler

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  do:
    uses: openkcm/build/.github/workflows/labeler.yaml@main
    secrets: inherit
